### ISSUE TITLE
可以根据不同应用切换网络吗？

### ISSUE THREAD

**Issue by JinYiTao** [lxy1992/mac-network-switch#12]
公司禁止了远程桌面应用，我mac网线连接公司网络，wif连接手机热点，如何让远程桌面软件使用 wifi 网络，其他的软件使用网络的网络

**Comment by lxy1992** [comment]
从官方的文档上，没有这种用法。虽然似乎有线网络和无线网络可以同时连接，但实际上，优先使用的是WiFi。

从公司禁止的角度来看， 大概率是从路由器和交换机那里，直接用名单禁止了，一般禁止的是域名和IP。你如果可以修改远程网络软件的请求地址域名地址，加上一个自己配置的代理服务器，理论上可以解决，但这需要你有对这个远程桌面软件逆向工程的能力。

其他的方式我就不太清楚了，也没有查到相关的信息

如果你研究出来了，欢迎分享。
