### ISSUE TITLE
能讲一下具体的使用方法吗？解压后都是文稿

### ISSUE THREAD

**Issue by different-shuai** [lxy1992/mac-network-switch#5]
能讲一下用法吗？<img width="752" alt="截屏2023-03-18 22 03 07" src="https://user-images.githubusercontent.com/79900549/226110870-afe32475-be45-4957-98f4-2871599064d3.png">

**Comment by telotortium** [comment]
@different-shuai 说明已经包含在README文件中。首先，您需要运行以下命令在您的机器上安装脚本：

```
go install github.com/lxy1992/mac-network-switch@latest
```

然后，运行以下命令开始自动切换WiFi，当以太网连接时关闭WiFi，当以太网断开连接时打开WiFi：

```
sudo mac-network-switch toggleAirport --switch start
```

然后您不需要做任何事情 - 这种自动切换将持续在重启后。只有当您想要禁用自动切换时，您才需要运行以下命令：

```
sudo mac-network-switch toggleAirport --switch stop
```

**Comment by telotortium** [comment]
@different-shuai 如果您想要从刚刚下载的包中进行安装，请按照以下步骤进行操作：

1. 打开Terminal.app。
2. 将包的顶级文件夹拖到Dock中的Terminal.app图标上，以在包的目录中打开终端。
3. 运行 go install。
4. 然后运行 sudo mac-network-switch toggleAirport --switch start。

**Comment by lxy1992** [comment]
@different-shuai 抱歉，最近几天没看github, @telotortium 解释的非常准确，按照这个说明可以解决。Thanks a ton for your help! @telotortium

**Comment by different-shuai** [comment]
> @different-shuai 如果您想要从刚刚下载的包中进行安装，请按照以下步骤进行操作：
> 
> 1. 打开 Terminal.app。
> 2. 将包的顶级文件夹拖到 Dock 中的 Terminal.app 图标上，以在包的目录中打开终端。
> 3. 运行 go install。
> 4. 然后运行 sudo mac-network-switch toggleAirport --switch start。

感谢！

**Comment by different-shuai** [comment]
> @different-shuai 抱歉，最近几天没看 github, @telotortium 解释的非常准确，按照这个说明可以解决。Thanks a ton for your help! @telotortium

感谢！
